# Generated by Django 5.2.3 on 2025-07-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_entidade_message_entidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_entidades/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='chat.entidade')),
            ],
        ),
    ]
