# Generated by Django 5.2.3 on 2025-07-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('script', models.FileField(upload_to='automations_scripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='chat.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RODANDO', 'Rodando'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('log_output', models.TextField(blank=True, help_text='Saída do console (stdout/stderr) da execução.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='automations.automacao')),
            ],
        ),
    ]
