# Generated by Django 5.2.3 on 2025-07-13 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('chat', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'PC do Financeiro', 'Servidor de Testes'", max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token de autenticação gerado automaticamente para o agente.', unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entidade', models.ForeignKey(help_text='A qual entidade este agente pertence?', on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='chat.entidade')),
            ],
        ),
    ]
